### ISSUE TITLE
File Export LOcation

### ISSUE THREAD

**Issue by athtest800** [uos/slam6d_exporter#2]
Hello!
In what location does it export the files?
Thank you.

**Comment by jspricke** [comment]
Hi,

it's writing to the directory where it was started from. If you use roslaunch, it's ~/.ros.

Cheers Jochen

**Comment by athtest800** [comment]
Thanks! I found them.
The problem is that I get very(!)strange results with slam6d tool.
I have a SICK 2D laser scanner (lms100) with imu MPU6050. is it possible to register the lidar data? Or I need also odometry?
I ask because the exported data from this module gave me wrong things.
Thank you again!

**Comment by jspricke** [comment]
Note that this is only the export utility for slam6d:

http://slam6d.sourceforge.net/

Registration usually needs some initial alignment, which could be
odometry.
